import type { ArrestRecord, SourceDocument } from "@/lib/types";

function avatar(name: string, ink: string): string {
  const parts = name.trim().split(/\s+/);
  const letters =
    parts.length === 1
      ? parts[0]!.slice(0, 2).toUpperCase()
      : `${parts[0]![0] ?? ""}${parts[parts.length - 1]![0] ?? ""}`.toUpperCase();
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="320" height="400" viewBox="0 0 320 400">
  <rect width="320" height="400" fill="${ink}"/>
  <circle cx="160" cy="168" r="64" fill="#f4efe6" opacity="0.14"/>
  <text x="160" y="184" text-anchor="middle" font-family="Georgia, serif" font-size="64" fill="#f4efe6">${letters}</text>
  <rect x="0" y="372" width="320" height="28" fill="#1a1814" opacity="0.35"/>
</svg>`;
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

const SAMPLE_DOC_ID = "sample-bulletin-aug";

export const SAMPLE_DOCUMENT: SourceDocument = {
  id: SAMPLE_DOC_ID,
  fileName: "sample-weekly-bulletin.pdf",
  uploadedAt: "2026-08-24T14:00:00.000Z",
  recordCount: 12,
  pageCount: 4,
};

export const SAMPLE_RECORDS: ArrestRecord[] = [
  {
    id: "sample-1",
    fullName: "Marcus Hale",
    gender: "male",
    caseNumber: "PD-26-18421",
    arrestedAt: "2026-08-22T16:42:00.000Z",
    retailer: "Harbor & Oak Market",
    charges: "Shoplifting",
    location: "Harbor & Oak Market, 410 Pine St",
    notes: "",
    photo: avatar("Marcus Hale", "#243447"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
  {
    id: "sample-2",
    fullName: "Elena Voss",
    gender: "female",
    caseNumber: "PD-26-18455",
    arrestedAt: "2026-08-21T11:18:00.000Z",
    retailer: "Northline Pharmacy",
    charges: "Theft of controlled merchandise",
    location: "Northline Pharmacy #18",
    notes: "",
    photo: avatar("Elena Voss", "#3d4a3a"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
  {
    id: "sample-3",
    fullName: "Jonah Reed",
    gender: "male",
    caseNumber: "PD-26-18302",
    arrestedAt: "2026-08-19T19:05:00.000Z",
    retailer: "Westfield Supercenter",
    charges: "Organized retail theft",
    location: "Westfield Supercenter, Bay 4",
    notes: "",
    photo: avatar("Jonah Reed", "#4a3b32"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
  {
    id: "sample-4",
    fullName: "Priya Nandakumar",
    gender: "female",
    caseNumber: "PD-26-18277",
    arrestedAt: "2026-08-18T13:27:00.000Z",
    retailer: "Lumen Home Goods",
    charges: "Shoplifting",
    location: "Lumen Home Goods — Riverside",
    notes: "",
    photo: avatar("Priya Nandakumar", "#2f3d4d"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
  {
    id: "sample-5",
    fullName: "Derrick Cole",
    gender: "male",
    caseNumber: "PD-26-18190",
    arrestedAt: "2026-08-16T09:51:00.000Z",
    retailer: "Westfield Supercenter",
    charges: "Trespass after warning",
    location: "Westfield Supercenter, grocery",
    notes: "",
    photo: avatar("Derrick Cole", "#3a3330"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
  {
    id: "sample-6",
    fullName: "Sofia Alvarez",
    gender: "female",
    caseNumber: "PD-26-18144",
    arrestedAt: "2026-08-15T17:33:00.000Z",
    retailer: "Harbor & Oak Market",
    charges: "Shoplifting",
    location: "Harbor & Oak Market, 410 Pine St",
    notes: "",
    photo: avatar("Sofia Alvarez", "#4a3944"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
  {
    id: "sample-7",
    fullName: "Theo Brandt",
    gender: "male",
    caseNumber: "PD-26-18088",
    arrestedAt: "2026-08-12T20:14:00.000Z",
    retailer: "Cinder Hardware",
    charges: "Theft",
    location: "Cinder Hardware, Dockside",
    notes: "",
    photo: avatar("Theo Brandt", "#2c3a32"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
  {
    id: "sample-8",
    fullName: "Amelia Cho",
    gender: "female",
    caseNumber: "PD-26-18021",
    arrestedAt: "2026-08-11T12:02:00.000Z",
    retailer: "Northline Pharmacy",
    charges: "Shoplifting",
    location: "Northline Pharmacy #18",
    notes: "",
    photo: avatar("Amelia Cho", "#243447"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
  {
    id: "sample-9",
    fullName: "Isaac Morrow",
    gender: "male",
    caseNumber: "PD-26-17960",
    arrestedAt: "2026-08-08T15:47:00.000Z",
    retailer: "Lumen Home Goods",
    charges: "Fraudulent return",
    location: "Lumen Home Goods — Riverside",
    notes: "",
    photo: avatar("Isaac Morrow", "#3d4a3a"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
  {
    id: "sample-10",
    fullName: "Nina Patel",
    gender: "female",
    caseNumber: "PD-26-17895",
    arrestedAt: "2026-08-05T10:19:00.000Z",
    retailer: "Westfield Supercenter",
    charges: "Shoplifting",
    location: "Westfield Supercenter, apparel",
    notes: "",
    photo: avatar("Nina Patel", "#4a3b32"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
  {
    id: "sample-11",
    fullName: "Calvin Ortiz",
    gender: "male",
    caseNumber: "PD-26-17740",
    arrestedAt: "2026-07-29T18:08:00.000Z",
    retailer: "Cinder Hardware",
    charges: "Theft of tools",
    location: "Cinder Hardware, Dockside",
    notes: "",
    photo: avatar("Calvin Ortiz", "#2f3d4d"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
  {
    id: "sample-12",
    fullName: "Harper Quinn",
    gender: "unknown",
    caseNumber: "PD-26-17612",
    arrestedAt: "2026-07-22T14:55:00.000Z",
    retailer: "Harbor & Oak Market",
    charges: "Shoplifting",
    location: "Harbor & Oak Market, 410 Pine St",
    notes: "Sex not listed on the source bulletin.",
    photo: avatar("Harper Quinn", "#3a3330"),
    sourceFileName: SAMPLE_DOCUMENT.fileName,
    sourceId: SAMPLE_DOC_ID,
    createdAt: "2026-08-24T14:00:00.000Z",
    isSample: true,
  },
];
